apiVersion: database.crossflux.io/v1alpha1
kind: Instance
metadata:
  name: my-db
  labels:
    db.aws.crossflux.io/db-id: default
spec:
  parameters:
    storageGB: 10
    dbName: myDb
  writeConnectionSecretToRef:
    name: app1-db
