apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: my-crossplane-vpc
  labels:
    networks.aws.crossflux.io/network-id: default
spec:
  forProvider:
    region: us-west-2
    cidrBlock: 172.31.0.0/16
    enableDnsSupport: true
    enableDnsHostNames: true
  deletionPolicy: Orphan
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: default
  labels:
    networks.aws.crossflux.io/network-id: default
spec:
  forProvider:
    region: us-west-2
    groupName: my-crossplane-vpc
    description: my VPC security group - updated
  deletionPolicy: Orphan
