apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: west-2a
  labels:
    zone: us-west-2a
    access: public
    networks.aws.crossflux.io/network-id: default
spec:
  forProvider:
    region: us-west-2
    mapPublicIPOnLaunch: true
    cidrBlock: 172.31.16.0/20
    availabilityZone: us-west-2a
    vpcRef:
      name: my-crossplane-vpc
    tags:
      - key: kubernetes.io/role/elb
        value: "1"
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: west-2b
  labels:
    zone: us-west-2b
    access: public
    networks.aws.crossflux.io/network-id: default
spec:
  forProvider:
    region: us-west-2
    mapPublicIPOnLaunch: true
    cidrBlock: 172.31.0.0/20
    availabilityZone: us-west-2b
    vpcRef:
      name: my-crossplane-vpc
    tags:
      - key: kubernetes.io/role/elb
        value: "1"
